config/routes.rb
Rails.application.routes.draw do
  get "tasks/today", to: "tasks#today"
  resources :tasks
  resources :categories
  devise_for :users
  root "categories#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "tasks/today", to: "tasks#today"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "categories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :tasks, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = current_user.categories
  end

  def show
  end
 
  def new
    @category = current_user.categories.new
  end

  def edit
  end

  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_category
      @category = current_user.categories.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = current_user.tasks

  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
  @task = Task.new
  @task.category_id = params[:category_id] if params[:category_id]
  end

  # GET /tasks/1/edit
  def edit
  end

  def today
  @tasks = current_user.tasks.where(due_date: Date.today)
  end

  # POST /tasks or /tasks.json
  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_path, status: :see_other, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = current_user.tasks.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.expect(task: [ :title, :description, :due_date, :category_id, :user_id ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= category.user_id %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categories" %>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<%= link_to "New Task for This Category", new_task_path(category_id: @category.id) %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Journal App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
  
  <% if user_signed_in? %>
  <p>Welcome, <%= current_user.email %> | <%= link_to 'Logout', destroy_user_session_path, method: :delete %></p>
  <%= link_to 'Categories', categories_path %>
  <%= link_to "Today's Tasks", tasks_today_path %>

  <% else %>
  <%= link_to 'Sign Up', new_user_registration_path %> |
  <%= link_to 'Login', new_user_session_path %>
  <%= link_to "Today's Tasks", tasks_today_path %>

  <% end %>
<hr>

    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div>
  <%= form.label :category_id style: "display: block" %>
  <%= form.collection_select :category_id, current_user.categories, :id, :name %>

  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= task.due_date %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= task.category_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= task.user_id %>
  </p>

</div>

app/views/tasks/edit.html.erb
<% content_for :title, "Editing task" %>

<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Tasks" %>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<% content_for :title, "New task" %>

<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>

app/views/tasks/today.html.erb
<h1>Tasks for Today</h1>

<% @tasks.each do |task| %>
  <p>
    <strong>Title:</strong> <%= task.title %><br>
    <strong>Description:</strong> <%= task.description %><br>
    <strong>Due:</strong> <%= task.due_date %>
  </p>
<% end %>